In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('mpg.csv')
df.sample(10)

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
91,ford,mustang,3.8,1999,6,auto(l4),r,18,25,r,subcompact
216,volkswagen,jetta,2.0,2008,4,manual(m6),f,21,29,p,compact
178,toyota,4runner 4wd,4.7,2008,8,auto(l5),4,14,17,r,suv
50,dodge,dakota pickup 4wd,3.9,1999,6,auto(l4),4,13,17,r,pickup
220,volkswagen,jetta,2.8,1999,6,manual(m5),f,17,24,r,compact
89,ford,f150 pickup 4wd,5.4,2008,8,auto(l4),4,13,17,r,pickup
160,subaru,forester awd,2.5,1999,4,auto(l4),4,18,24,r,suv
71,dodge,ram 1500 pickup 4wd,5.2,1999,8,manual(m5),4,11,16,r,pickup
21,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv
165,subaru,impreza awd,2.2,1999,4,auto(l4),4,21,26,r,subcompact

In [7]:
df.manufacturer == 'audi'

0       True
1       True
2       True
3       True
4       True
       ...
229    False
230    False
231    False
232    False
233    False
Name: manufacturer, Length: 234, dtype: bool

In [9]:
df[df.manufacturer == 'audi']

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
5,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact
6,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact
7,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact
8,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact
9,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact
10,audi,a4 quattro,2.0,2008,4,auto(s6),4,19,27,p,compact
11,audi,a4 quattro,2.8,1999,6,auto(l5),4,15,25,p,compact
12,audi,a4 quattro,2.8,1999,6,manual(m5),4,17,25,p,compact
13,audi,a4 quattro,3.1,2008,6,auto(s6),4,17,25,p,compact
14,audi,a4 quattro,3.1,2008,6,manual(m6),4,15,25,p,compact
15,audi,a6 quattro,2.8,1999,6,auto(l5),4,15,24,p,midsize
16,audi,a6 quattro,3.1,2008,6,auto(s6),4,17,25,p,midsize
17,audi,a6 quattro,4.2,2008,8,auto(s6),4,16,23,p,midsize

In [10]:
df[df.manufacturer != 'audi']

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
18,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
19,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,11,15,e,suv
20,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
21,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv
22,chevrolet,c1500 suburban 2wd,6.0,2008,8,auto(l4),r,12,17,r,suv
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [14]:
df[df.cty > 30]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
212,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact
221,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact

In [18]:
df[(df.manufacturer == 'toyota') & (df.cty > 25)]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
195,toyota,corolla,1.8,1999,4,manual(m5),f,26,35,r,compact
196,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact
197,toyota,corolla,1.8,2008,4,auto(l4),f,26,35,r,compact

In [19]:
df[(df.manufacturer == 'toyota') | (df.cty > 25)]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
99,honda,civic,1.6,1999,4,manual(m5),f,28,33,r,subcompact
104,honda,civic,1.8,2008,4,manual(m5),f,26,34,r,subcompact
173,toyota,4runner 4wd,2.7,1999,4,manual(m5),4,15,20,r,suv
174,toyota,4runner 4wd,2.7,1999,4,auto(l4),4,16,20,r,suv
175,toyota,4runner 4wd,3.4,1999,6,auto(l4),4,15,19,r,suv
176,toyota,4runner 4wd,3.4,1999,6,manual(m5),4,15,17,r,suv
177,toyota,4runner 4wd,4.0,2008,6,auto(l5),4,16,20,r,suv
178,toyota,4runner 4wd,4.7,2008,8,auto(l5),4,14,17,r,suv
179,toyota,camry,2.2,1999,4,manual(m5),f,21,29,r,midsize
180,toyota,camry,2.2,1999,4,auto(l4),f,21,27,r,midsize
181,toyota,camry,2.4,2008,4,manual(m5),f,21,31,r,midsize
182,toyota,camry,2.4,2008,4,auto(l5),f,21,31,r,midsize
183,toyota,camry,3.0,1999,6,auto(l4),f,18,26,r,midsize
184,toyota,camry,3.0,1999,6,manual(m5),f,18,26,r,midsize
185,toyota,camry,3.5,2008,6,auto(s6),f,19,28,r,midsize
186,toyota,camry solara,2.2,1999,4,auto(l4),f,21,27,r,compact
187,toyota,camry solara,2.2,1999,4,manual(m5),f,21,29,r,compact
188,toyota,camry solara,2.4,2008,4,manual(m5),f,21,31,r,compact
189,toyota,camry solara,2.4,2008,4,auto(s5),f,22,31,r,compact
190,toyota,camry solara,3.0,1999,6,auto(l4),f,18,26,r,compact
191,toyota,camry solara,3.0,1999,6,manual(m5),f,18,26,r,compact
192,toyota,camry solara,3.3,2008,6,auto(s5),f,18,27,r,compact
193,toyota,corolla,1.8,1999,4,auto(l3),f,24,30,r,compact
194,toyota,corolla,1.8,1999,4,auto(l4),f,24,33,r,compact
195,toyota,corolla,1.8,1999,4,manual(m5),f,26,35,r,compact
196,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact
197,toyota,corolla,1.8,2008,4,auto(l4),f,26,35,r,compact
198,toyota,land cruiser wagon 4wd,4.7,1999,8,auto(l4),4,11,15,r,suv
199,toyota,land cruiser wagon 4wd,5.7,2008,8,auto(s6),4,13,18,r,suv
200,toyota,toyota tacoma 4wd,2.7,1999,4,manual(m5),4,15,20,r,pickup
201,toyota,toyota tacoma 4wd,2.7,1999,4,auto(l4),4,16,20,r,pickup
202,toyota,toyota tacoma 4wd,2.7,2008,4,manual(m5),4,17,22,r,pickup
203,toyota,toyota tacoma 4wd,3.4,1999,6,manual(m5),4,15,17,r,pickup
204,toyota,toyota tacoma 4wd,3.4,1999,6,auto(l4),4,15,19,r,pickup
205,toyota,toyota tacoma 4wd,4.0,2008,6,manual(m6),4,15,18,r,pickup
206,toyota,toyota tacoma 4wd,4.0,2008,6,auto(l5),4,16,20,r,pickup
212,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact
221,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact
222,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact

In [20]:
df[df.manufacturer.isin(['toyoya','nissan','honda'])]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
99,honda,civic,1.6,1999,4,manual(m5),f,28,33,r,subcompact
100,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact
101,honda,civic,1.6,1999,4,manual(m5),f,25,32,r,subcompact
102,honda,civic,1.6,1999,4,manual(m5),f,23,29,p,subcompact
103,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact
104,honda,civic,1.8,2008,4,manual(m5),f,26,34,r,subcompact
105,honda,civic,1.8,2008,4,auto(l5),f,25,36,r,subcompact
106,honda,civic,1.8,2008,4,auto(l5),f,24,36,c,subcompact
107,honda,civic,2.0,2008,4,manual(m6),f,21,29,p,subcompact
141,nissan,altima,2.4,1999,4,manual(m5),f,21,29,r,compact
142,nissan,altima,2.4,1999,4,auto(l4),f,19,27,r,compact
143,nissan,altima,2.5,2008,4,auto(av),f,23,31,r,midsize
144,nissan,altima,2.5,2008,4,manual(m6),f,23,32,r,midsize
145,nissan,altima,3.5,2008,6,manual(m6),f,19,27,p,midsize
146,nissan,altima,3.5,2008,6,auto(av),f,19,26,p,midsize
147,nissan,maxima,3.0,1999,6,auto(l4),f,18,26,r,midsize
148,nissan,maxima,3.0,1999,6,manual(m5),f,19,25,r,midsize
149,nissan,maxima,3.5,2008,6,auto(av),f,19,25,p,midsize
150,nissan,pathfinder 4wd,3.3,1999,6,auto(l4),4,14,17,r,suv
151,nissan,pathfinder 4wd,3.3,1999,6,manual(m5),4,15,17,r,suv
152,nissan,pathfinder 4wd,4.0,2008,6,auto(l5),4,14,20,p,suv
153,nissan,pathfinder 4wd,5.6,2008,8,auto(s5),4,12,18,p,suv

In [21]:
df[~df.manufacturer.isin(['toyoya','nissan','honda'])]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

TypeError: unhashable type: 'list'