In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print(f'pandas version: {pd.__version__}')

pandas version: 2.2.0

In [3]:
from datetime import datetime
str(datetime.now())

'2024-02-24 08:16:36.370779'

In [4]:
url = 'https://en.wikipedia.org/wiki/List_of_tallest_buildings#Height_to_roof'
dfs = pd.read_html('https://en.wikipedia.org/wiki/List_of_tallest_buildings#Height_to_roof',
                  header=0,

SyntaxError: incomplete input (829345496.py, line 4)

In [ ]:
dfs[1].info()

In [ ]:
dfs[1].sample(10)

In [ ]:
df = dfs[1].drop(columns='Unnamed: 9', axis= 1)
df

In [ ]:
df.drop([0,1], inplace=True)
df

In [ ]:
df['rank'] = df['rank'].astype(int)

In [ ]:
df.info()

In [ ]:
df.rename(columns={'Unnamed: 0':'rank'}, inplace=True)
df.rename(columns={'Height[14]':'Height[m]'}, inplace=True)

df

In [11]:
iphone_data = {
    "iphone_model": ["5s", "6", "6s", "7", "7 Plus", "8", "8 Plus", "X", "XR", "XS", "XS Max", "11", "11 Pro", "11 Pro Max", "12 mini", "12", "12 Pro", "12 Pro Max", "13 mini", "13", "13 Pro", "13 Pro Max", "14", "14 Plus", "14 Pro", "14 Pro Max", "15"],
    "release_date": ["September 2013", "September 2014", "September 2015", "September 2016", "September 2016", "September 2017", "September 2017", "November 2017", "September 2018", "September 2018", "September 2018", "September 2019", "September 2019", "September 2019", "September 2020", "September 2020", "October 2020", "November 2020", "September 2021", "September 2021", "September 2021", "September 2021", "September 2022", "September 2022", "September 2022", "September 2022", "September 2023"],
    "cpu": ["Apple A7", "Apple A8", "Apple A9", "Apple A10 Fusion", "Apple A10 Fusion", "Apple A11 Bionic", "Apple A11 Bionic", "Apple A11 Bionic", "Apple A12 Bionic", "Apple A12 Bionic", "Apple A12 Bionic", "Apple A13 Bionic", "Apple A13 Bionic", "Apple A13 Bionic", "Apple A14 Bionic", "Apple A14 Bionic", "Apple A14 Bionic", "Apple A14 Bionic", "Apple A15 Bionic", "Apple A15 Bionic", "Apple A15 Bionic", "Apple A15 Bionic", "Apple A16 Bionic", "Apple A16 Bionic", "Apple A16 Bionic", "Apple A16 Bionic", "Apple A17 Bionic"],
    "opening_price": [499, 649, 649, 649, 749, 699, 799, 999, 749, 999, 1099, 499, 999, 1099, 699, 799, 899, 1099, 699, 799, 999, 1099, 799, 899, 999, 1099, 799]
}

In [13]:
df1 = pd.DataFrame(iphone_data)
df1

   iphone_model    release_date               cpu  opening_price
0            5s  September 2013          Apple A7            499
1             6  September 2014          Apple A8            649
2            6s  September 2015          Apple A9            649
3             7  September 2016  Apple A10 Fusion            649
4        7 Plus  September 2016  Apple A10 Fusion            749
5             8  September 2017  Apple A11 Bionic            699
6        8 Plus  September 2017  Apple A11 Bionic            799
7             X   November 2017  Apple A11 Bionic            999
8            XR  September 2018  Apple A12 Bionic            749
9            XS  September 2018  Apple A12 Bionic            999
10       XS Max  September 2018  Apple A12 Bionic           1099
11           11  September 2019  Apple A13 Bionic            499
12       11 Pro  September 2019  Apple A13 Bionic            999
13   11 Pro Max  September 2019  Apple A13 Bionic           1099
14      12 mini  September 2020  Apple A14 Bionic            699
15           12  September 2020  Apple A14 Bionic            799
16       12 Pro    October 2020  Apple A14 Bionic            899
17   12 Pro Max   November 2020  Apple A14 Bionic           1099
18      13 mini  September 2021  Apple A15 Bionic            699
19           13  September 2021  Apple A15 Bionic            799
20       13 Pro  September 2021  Apple A15 Bionic            999
21   13 Pro Max  September 2021  Apple A15 Bionic           1099
22           14  September 2022  Apple A16 Bionic            799
23      14 Plus  September 2022  Apple A16 Bionic            899
24       14 Pro  September 2022  Apple A16 Bionic            999
25   14 Pro Max  September 2022  Apple A16 Bionic           1099
26           15  September 2023  Apple A17 Bionic            799

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iphone_model   27 non-null     object
 1   release_date   27 non-null     object
 2   cpu            27 non-null     object
 3   opening_price  27 non-null     int64
dtypes: int64(1), object(3)
memory usage: 996.0+ bytes

In [23]:
df1['iphone_model']

0             5s
1              6
2             6s
3              7
4         7 Plus
5              8
6         8 Plus
7              X
8             XR
9             XS
10        XS Max
11            11
12        11 Pro
13    11 Pro Max
14       12 mini
15            12
16        12 Pro
17    12 Pro Max
18       13 mini
19            13
20        13 Pro
21    13 Pro Max
22            14
23       14 Plus
24        14 Pro
25    14 Pro Max
26            15
Name: iphone_model, dtype: object

In [53]:
df1['variant'] = df1.iphone_model.str.extract(r'\w\s(\w+\s*\w*)')
df1

,iphone_model,release_date,cpu,opening_price,variant,variant_2
0,5s,September 2013,Apple A7,499,NaN,NaN
1,6,September 2014,Apple A8,649,NaN,NaN
2,6s,September 2015,Apple A9,649,NaN,NaN
3,7,September 2016,Apple A10 Fusion,649,NaN,NaN
4,7 Plus,September 2016,Apple A10 Fusion,749,Plus,NaN
5,8,September 2017,Apple A11 Bionic,699,NaN,NaN
6,8 Plus,September 2017,Apple A11 Bionic,799,Plus,NaN
7,X,November 2017,Apple A11 Bionic,999,NaN,NaN
8,XR,September 2018,Apple A12 Bionic,749,NaN,NaN
9,XS,September 2018,Apple A12 Bionic,999,NaN,NaN
10,XS Max,September 2018,Apple A12 Bionic,1099,Max,NaN
11,11,September 2019,Apple A13 Bionic,499,NaN,NaN
12,11 Pro,September 2019,Apple A13 Bionic,999,Pro,NaN
13,11 Pro Max,September 2019,Apple A13 Bionic,1099,Pro Max,Pro Max
14,12 mini,September 2020,Apple A14 Bionic,699,mini,NaN
15,12,September 2020,Apple A14 Bionic,799,NaN,NaN
16,12 Pro,October 2020,Apple A14 Bionic,899,Pro,NaN
17,12 Pro Max,November 2020,Apple A14 Bionic,1099,Pro Max,Pro Max
18,13 mini,September 2021,Apple A15 Bionic,699,mini,NaN
19,13,September 2021,Apple A15 Bionic,799,NaN,NaN
20,13 Pro,September 2021,Apple A15 Bionic,999,Pro,NaN
21,13 Pro Max,September 2021,Apple A15 Bionic,1099,Pro Max,Pro Max
22,14,September 2022,Apple A16 Bionic,799,NaN,NaN
23,14 Plus,September 2022,Apple A16 Bionic,899,Plus,NaN
24,14 Pro,September 2022,Apple A16 Bionic,999,Pro,NaN
25,14 Pro Max,September 2022,Apple A16 Bionic,1099,Pro Max,Pro Max
26,15,September 2023,Apple A17 Bionic,799,NaN,NaN

In [130]:
df1.cpu = df1.cpu.str.replace(r'[Aa]pple', '', regex=True)
df1['iphone_model'] = df1['iphone_model'].str.extract(r'(\w+)')
df1

,iphone_model,release_date,cpu,opening_price,variant,clean,iphone_model_clearn
0,5s,September 2013,A7,499,NaN,NaN,5s
1,6,September 2014,A8,649,NaN,NaN,6
2,6s,September 2015,A9,649,NaN,NaN,6s
3,7,September 2016,A10 Fusion,649,NaN,NaN,7
4,7,September 2016,A10 Fusion,749,Plus,Plus,7
5,8,September 2017,A11 Bionic,699,NaN,NaN,8
6,8,September 2017,A11 Bionic,799,Plus,Plus,8
7,X,November 2017,A11 Bionic,999,NaN,NaN,X
8,XR,September 2018,A12 Bionic,749,NaN,NaN,XR
9,XS,September 2018,A12 Bionic,999,NaN,NaN,XS
10,XS,September 2018,A12 Bionic,1099,Max,Max,XS
11,11,September 2019,A13 Bionic,499,NaN,NaN,11
12,11,September 2019,A13 Bionic,999,Pro,Pro,11
13,11,September 2019,A13 Bionic,1099,Pro Max,Pro Max,11
14,12,September 2020,A14 Bionic,699,mini,mini,12
15,12,September 2020,A14 Bionic,799,NaN,NaN,12
16,12,October 2020,A14 Bionic,899,Pro,Pro,12
17,12,November 2020,A14 Bionic,1099,Pro Max,Pro Max,12
18,13,September 2021,A15 Bionic,699,mini,mini,13
19,13,September 2021,A15 Bionic,799,NaN,NaN,13
20,13,September 2021,A15 Bionic,999,Pro,Pro,13
21,13,September 2021,A15 Bionic,1099,Pro Max,Pro Max,13
22,14,September 2022,A16 Bionic,799,NaN,NaN,14
23,14,September 2022,A16 Bionic,899,Plus,Plus,14
24,14,September 2022,A16 Bionic,999,Pro,Pro,14
25,14,September 2022,A16 Bionic,1099,Pro Max,Pro Max,14
26,15,September 2023,A17 Bionic,799,NaN,NaN,15

In [132]:
df1.drop(columns='iphone_model_clearn', inplace=True)

In [134]:
df1

   iphone_model    release_date          cpu  opening_price  variant    clean
0            5s  September 2013           A7            499      NaN      NaN
1             6  September 2014           A8            649      NaN      NaN
2            6s  September 2015           A9            649      NaN      NaN
3             7  September 2016   A10 Fusion            649      NaN      NaN
4             7  September 2016   A10 Fusion            749     Plus     Plus
5             8  September 2017   A11 Bionic            699      NaN      NaN
6             8  September 2017   A11 Bionic            799     Plus     Plus
7             X   November 2017   A11 Bionic            999      NaN      NaN
8            XR  September 2018   A12 Bionic            749      NaN      NaN
9            XS  September 2018   A12 Bionic            999      NaN      NaN
10           XS  September 2018   A12 Bionic           1099      Max      Max
11           11  September 2019   A13 Bionic            499      NaN      NaN
12           11  September 2019   A13 Bionic            999      Pro      Pro
13           11  September 2019   A13 Bionic           1099  Pro Max  Pro Max
14           12  September 2020   A14 Bionic            699     mini     mini
15           12  September 2020   A14 Bionic            799      NaN      NaN
16           12    October 2020   A14 Bionic            899      Pro      Pro
17           12   November 2020   A14 Bionic           1099  Pro Max  Pro Max
18           13  September 2021   A15 Bionic            699     mini     mini
19           13  September 2021   A15 Bionic            799      NaN      NaN
20           13  September 2021   A15 Bionic            999      Pro      Pro
21           13  September 2021   A15 Bionic           1099  Pro Max  Pro Max
22           14  September 2022   A16 Bionic            799      NaN      NaN
23           14  September 2022   A16 Bionic            899     Plus     Plus
24           14  September 2022   A16 Bionic            999      Pro      Pro
25           14  September 2022   A16 Bionic           1099  Pro Max  Pro Max
26           15  September 2023   A17 Bionic            799      NaN      NaN

In [136]:
df1['release_date'] = pd.to_datetime(df1['release_date'], format='%B %Y')

In [137]:
df1

   iphone_model release_date          cpu  opening_price  variant    clean
0            5s   2013-09-01           A7            499      NaN      NaN
1             6   2014-09-01           A8            649      NaN      NaN
2            6s   2015-09-01           A9            649      NaN      NaN
3             7   2016-09-01   A10 Fusion            649      NaN      NaN
4             7   2016-09-01   A10 Fusion            749     Plus     Plus
5             8   2017-09-01   A11 Bionic            699      NaN      NaN
6             8   2017-09-01   A11 Bionic            799     Plus     Plus
7             X   2017-11-01   A11 Bionic            999      NaN      NaN
8            XR   2018-09-01   A12 Bionic            749      NaN      NaN
9            XS   2018-09-01   A12 Bionic            999      NaN      NaN
10           XS   2018-09-01   A12 Bionic           1099      Max      Max
11           11   2019-09-01   A13 Bionic            499      NaN      NaN
12           11   2019-09-01   A13 Bionic            999      Pro      Pro
13           11   2019-09-01   A13 Bionic           1099  Pro Max  Pro Max
14           12   2020-09-01   A14 Bionic            699     mini     mini
15           12   2020-09-01   A14 Bionic            799      NaN      NaN
16           12   2020-10-01   A14 Bionic            899      Pro      Pro
17           12   2020-11-01   A14 Bionic           1099  Pro Max  Pro Max
18           13   2021-09-01   A15 Bionic            699     mini     mini
19           13   2021-09-01   A15 Bionic            799      NaN      NaN
20           13   2021-09-01   A15 Bionic            999      Pro      Pro
21           13   2021-09-01   A15 Bionic           1099  Pro Max  Pro Max
22           14   2022-09-01   A16 Bionic            799      NaN      NaN
23           14   2022-09-01   A16 Bionic            899     Plus     Plus
24           14   2022-09-01   A16 Bionic            999      Pro      Pro
25           14   2022-09-01   A16 Bionic           1099  Pro Max  Pro Max
26           15   2023-09-01   A17 Bionic            799      NaN      NaN

In [147]:
df1.loc[df1['variant'] == 'Pro Max',['iphone_model','opening_price']]

   iphone_model  opening_price
13           11           1099
17           12           1099
21           13           1099
25           14           1099